---

- name: Distribution
  debug: 
    msg: "{{ hostvars[inventory_hostname].ansible_distribution }}"
- name: Distribution version
  debug: 
    msg: "{{ hostvars[inventory_hostname].ansible_distribution_version }}"
- name: Distribution major version    
  debug: 
    msg: "{{ hostvars[inventory_hostname].ansible_distribution_major_version }}"


- name: Ensure git is installed (RedHat).
  package:
    name: git
    state: '{{git_state}}'
    enablerepo: "{{ git_enablerepo | default(omit, true) }}"
  when:
    - ansible_os_family == 'RedHat'

- name: Update apt cache (Debian).
  apt: update_cache=true cache_valid_time=86400
  when: ansible_os_family == 'Debian'


- name: Ensure git is installed (Debian).
  apt:
    name: git
    state: '{{git_state}}'
  when:
    - ansible_os_family == 'Debian'